# Site settings
title: GTK-rs
description: > # this means to ignore newlines until "baseurl:"
  Rust bindings for GTK and GLib-based libraries
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://gtk-rs.org" # the base hostname & protocol for your site
github_username: gtk-rs
permalink: /blog/:year/:month/:day/:title.html
authors:
  gkoz: '<a href="https://github.com/gkoz">Gleb Kozyrev</a>'
  imperio: '<a href="https://github.com/GuillaumeGomez">Guillaume Gomez</a>'
exclude:
  - CNAME
  - README.md
  - "Gemfile*"
  - "*.sh"
  - vendor

# Build settings
markdown: kramdown
